version: '3.3'

services:
  web:
    container_name: twrk_back_web
    restart: always
    build:
      context: ./
      dockerfile: _docker/Dockerfile
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./:/home/twrk_back
      - static_volume:/home/twrk_back/static
      - ./media:/home/twrk_back/media
    ports:
      - 8000:8000
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=db
      - DJANGO_SUPERUSER_PASSWORD=admin
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_EMAIL=admin@admin.ru
    depends_on:
      - db

  db:
    container_name: twrk_back_db
    image: postgres:13.3
    restart: always
    hostname: postgres
    env_file:
      - .env
    environment:
      POSTGRES_DB: '${POSTGRES_DB}'
      POSTGRES_USER: '${POSTGRES_USER}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
      CONFIGS: "listen_addresses:'*',max_replication_slots:5"
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres/:/var/lib/postgresql/data
    healthcheck:
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  static_volume:
  media_volume: