version: '3.3'

services:
  db:
    container_name: sol_fac_db
    image: postgres:13.3
    restart: always
    hostname: postgres
    env_file:
      - .env
    environment:
      POSTGRES_DB: '${POSTGRES_DB}'
      POSTGRES_USER: '${POSTGRES_USER}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
      CONFIGS: "listen_addresses:'*',max_replication_slots:5"
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres/:/var/lib/postgresql/data
    healthcheck:
      interval: 5s
      timeout: 5s
      retries: 5