# Generated by Django 4.1.4 on 2022-12-13 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="description"),
        ),
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="media/products", verbose_name="image"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=11, verbose_name="price"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="status",
            field=models.CharField(
                choices=[
                    ("in_stock", "in_stock"),
                    ("out_of_stock", "out_of_stock"),
                    ("on_command", "on_command"),
                    ("waiting_receipt", "waiting_receipt"),
                    ("dont_produce", "dont_produce"),
                ],
                default="in_stock",
                max_length=15,
                verbose_name="status",
            ),
        ),
    ]
